# Navigation Links
# ALL LINKS MUST BE LOWER_CASE
#   To link a homepage section, specify the URL as a hash `#` followed by the filename of the
#     desired section in `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# This is the default-language menu
# Specific values needing translation must be provided in languages.toml

[[main]]
name = "Home"
url = "/"          # Home page top
weight = 10

[[main]]
name = "Safeguarding"
url = "/06_policies/01_safeguardingpolicy"
weight = 30

[[main]]
name = "Connect"
url = "/04_pray" 
weight = 40

[[main]]
name = "Login"
url = "user-login"
weight = 100

[[main]]
name = "Secure"
url = "/07_secure"
weight = 110


  
