[Hugo Website Root]
   C:\Hugo\Sites\TnT.Chinley
[Docx Root]
   C:\Hugo\Sites\TnT.Chinley\Source_Pages
[Docx Language]
   en
[Dotx Template Path]
   LifeForLiberia_Training_Styles.dotx
[Languages]
   [en]
[DateChanged]
   2023-07-21 17:48:09.608297