# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# This is the default-language menu
# Specific values needing translation must be provided in languages.toml

[[main]]
  name = "TnT"
  url = "#TnT_Webpage"
  weight = 10
  
[[main]]
  name = "Contact Us"
  url = "#contact"
  weight = 20
  
